spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blog
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

kakao.api-token: de4d3e0e26ed6e11acdd2a8917e54ee3
naver:
  client-id: _JhGHQt96KsZ5ibUmV_p
  client-secret: kspiNwjkVs

